name: Build, Test, and Deploy Laravel Application

on:
  push:
    branches:
      - main

jobs:
  build-test-deploy:
    runs-on: self-hosted  # Specifies to use the self-hosted runner
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Install Composer dependencies
        run: |
          cd /var/www/html/laravel-todolist-api-main
          composer install --no-interaction --prefer-dist --optimize-autoloader

      - name: Run tests
        run: |
          cd /var/www/html/laravel-todolist-api-main
          php artisan test

      - name: Deploy application
        run: |
          cd /var/www/html/laravel-todolist-api-main
          php artisan migrate --force
          php artisan config:cache
          php artisan route:cache
          php artisan view:cache
          sudo systemctl restart php8.1-fpm
          sudo systemctl restart nginx

