name: Build, Test, and Deploy Laravel Application

on:
  push:
    branches:
      - main

jobs:
  build-test-deploy:
    runs-on: self-hosted
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Copy .env file
        run: |
          sudo cp /tmp/.env /var/www/html/laravel-todolist-api-main/.env

      - name: Sync repository to deployment folder
        run: |
          sudo rsync -a --delete ${GITHUB_WORKSPACE}/ /var/www/html/laravel-todolist-api-main/

      - name: Install Composer dependencies
        run: |
          cd /var/www/html/laravel-todolist-api-main
          composer install --no-interaction --prefer-dist --optimize-autoloader

      - name: Generate application key if not set
        run: |
          cd /var/www/html/laravel-todolist-api-main
          php artisan key:generate --force

      - name: Run tests
        run: |
          cd /var/www/html/laravel-todolist-api-main
          php artisan test

      - name: Deploy application
        run: |
          cd /var/www/html/laravel-todolist-api-main
          php artisan migrate --force
          php artisan config:cache
          php artisan route:cache
          php artisan view:cache
          sudo systemctl restart php8.3-fpm
          sudo systemctl restart nginx
