name: Deploy Updated Laravel Application

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Sync updated files to deployment folder
        run: |
          sudo rsync -a --delete --exclude='.env' ${GITHUB_WORKSPACE}/ /var/www/html/laravel-todolist-api-main/

      - name: Install Composer dependencies
        run: |
          cd /var/www/html/laravel-todolist-api-main
          composer install --no-interaction --prefer-dist --optimize-autoloader

      - name: Run tests
        run: |
          cd /var/www/html/laravel-todolist-api-main
          php artisan test || exit 0  # Continue even if tests fail, or you can remove "|| exit 0" to halt on failure

      - name: Deploy application changes
        run: |
          cd /var/www/html/laravel-todolist-api-main
          php artisan migrate --force
          php artisan config:cache
          php artisan route:cache
          php artisan view:cache
          sudo systemctl restart php8.1-fpm
          sudo systemctl restart nginx
